### ISSUE TITLE
Import is removed on save

### ISSUE THREAD

**Issue by eliangidoni** [DamnWidget/anaconda_go#12]
Guys I have an issue with imports. When I save a file a valid import is removed from the import list. This happens for import list method:
```
import (
      'xxxx'
)
```
Is this a goimports bug ?

**Comment by DamnWidget** [comment]
Are you sure that the import is being used in your code? goimports will remove any unused import from the code.

**Comment by eliangidoni** [comment]
I'm totally sure. Thing is it seems there is a bug in goimports or gofmt ??
See https://github.com/joefitzgerald/go-plus/issues/52
The import I'm using is this
```
import(
    "gopkg.in/DATA-DOG/go-sqlmock.v1"
)
```

**Comment by eliangidoni** [comment]
Actually could it be a go path issue ? Not sure.....

**Comment by eliangidoni** [comment]
@DamnWidget Can I disable goimports and use gofmt instead ?

**Comment by DamnWidget** [comment]
What happens if you use `goimports` on the file from the terminal?

**Comment by DamnWidget** [comment]
This must be fixed now
