### ISSUE TITLE
CPU usage on OS X

### ISSUE THREAD

**Issue by sdemura** [DamnWidget/anaconda_go#14]
Every time I open Sublime and there's go code in the project I'm working on, my CPU fan goes crazy. Looks like 'guru' is indexing _every_ time I open sublime, even when `"anaconda_go_packages_cache_persistence": true` is set.

**Comment by DamnWidget** [comment]
The cache index is per project basis, so if you open a different directory that contains Go code it will index a new index under that directory name in the cache directory (probably stupid as it would really check for different GOPATHS and not project directories).

Can you check what is in your `~/Library/Cache/Anaconda/Go` directory?

**Comment by sdemura** [comment]
Ah, that's good to know.

As for my cache folder, here's an example.
```
~$ find ~/Library/cache/anaconda/ -type f -exec ls -lrth {} \;
-rw-r--r--  1 sean  staff     2B Feb  3 15:41 /Users/sean/Library/cache/anaconda//anaconda-2/packages.cache
-rw-r--r--  1 sean  staff     2B Feb  3 09:56 /Users/sean/Library/cache/anaconda//anaconda-4/packages.cache
-rw-r--r--  1 sean  staff     2B Feb 16 14:30 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
-rw-r--r--  1 sean  staff    82M May  9 10:43 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
-rw-r--r--  1 sean  staff     2B Feb  3 15:04 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
-rw-r--r--  1 sean  staff    82M May  9 11:03 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
-rw-r--r--  1 sean  staff     2B Feb  3 14:26 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
-rw-r--r--  1 sean  staff     2B Feb  2 12:34 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
-rw-r--r--  1 sean  staff     2B Feb 17 09:31 /Users/sean/Library/cache/anaconda//<some-folder>packages.cache
-rw-r--r--  1 sean  staff     2B Feb  3 16:14 /Users/sean/Library/cache/anaconda//<some-folder>/packages.cache
```

What bugs me about creating an index on each project is that in the example above, the two 82MB cache files are indices of the same root $GOPATH. I work on many projects inside my GOPATH, and to have a index of each is a bit of a pain.

VSCode and vim-go both leverage guru, but don't thrash my CPU like Anaconda_go does. Perhaps they index (don't index) differently?

**Comment by DamnWidget** [comment]
Yeah, not my smartest implementation. I will try to change that to index only when a different GOPATH is used and not when a different project/directory is being worked on.

I don't think VSCode or vim-go index any data, anaconda_go index it for it's own purposes.

Thanks for raising this, I totally missed it.

**Comment by DamnWidget** [comment]
I fixed this, will be live on next release

**Comment by sdemura** [comment]
Awesome! Looking forward it!
