### ISSUE TITLE
Every tab completion retriggers a scan of $GOPATH

### ISSUE THREAD

**Issue by alecthomas** [DamnWidget/anaconda_go#4]
At least that's what it looks like is happening. I've attached a screenshot. This happened about four or five times, then stopped...

This is happening every time Anaconda_GO tries to perform autocompletion. There are some errors in the list about git not being able to pull multiple branches (or something like that, sorry, the errors have subsequently disappeared).

![image](https://cloud.githubusercontent.com/assets/41767/23040472/89e81812-f4e5-11e6-886a-7a34f3b77b81.png)

**Comment by alecthomas** [comment]
Okay, here is an example of the error I'm seeing:

```
# cd /Users/aat/Development/go/src/gopkg.in/alecthomas/gometalinter.v1; git pull --ff-only
fatal: Cannot rebase onto multiple branches.
package gopkg.in/alecthomas/gometalinter.v1: exit status 128
```

However, when I run this command myself it succeeds, so I'm not sure where to go from here.

```
$ cd /Users/aat/Development/go/src/gopkg.in/alecthomas/gometalinter.v1; git pull --ff-only
Current branch master is up to date.
$ 
```

I then end up with this error popping up:

![image](https://cloud.githubusercontent.com/assets/41767/23040709/66481370-f4e6-11e6-90aa-76dc24db1029.png)

**Comment by DamnWidget** [comment]
That pull is being done by `go get` I think this can be related to two different possibilities.
* The most probable: Other plugin is interfering with anaconda go 
* Improbable: As you are the gometalinter author your gometalinter directory is in a non standard state? (because you being working on it)

**Comment by alecthomas** [comment]
I had disabled all other Go plugins that I could find: GoGuru, Godef, GoSublime... the gometalinter option was a good pickup, but unfortunately no, I have a normal copy of gometalinter.v1. The same error occurs with a bunch of other packages too... really weird.

**Comment by alecthomas** [comment]
What's the "root" go get command you're calling? Is it for each package individually?

**Comment by DamnWidget** [comment]
Can you check if the following is in your `$GOPATH`?:
```python
_go_dependencies = [
          'github.com/DamnWidget/godef',
          'golang.org/x/tools/cmd/guru',
          'github.com/fatih/motion',
          'github.com/josharian/impl',
          'github.com/nsf/gocode',
          'github.com/zmb3/gogetdoc',
          'gopkg.in/alecthomas/gometalinter.v1'
      ]
```

**Comment by alecthomas** [comment]
```
[aat@cavern:~/.go]cd $GOPATH/src
[aat@cavern:~/.go/src]ls -d 'github.com/DamnWidget/godef' 'golang.org/x/tools/cmd/guru' 'github.com/fatih/motion' 'github.com/josharian/impl' 'github.com/nsf/gocode' 'github.com/zmb3/gogetdoc' 'gopkg.in/alecthomas/gometalinter.v1'
ls: github.com/DamnWidget/godef: No such file or directory
github.com/fatih/motion/             github.com/nsf/gocode/               golang.org/x/tools/cmd/guru/
github.com/josharian/impl/           github.com/zmb3/gogetdoc/            gopkg.in/alecthomas/gometalinter.v1/
```

(btw I am in gitter if you'd prefer to chat there)

**Comment by alecthomas** [comment]
This was an issue with one package in my `GOPATH` having an edit. Strangely, it wasn't the ones being reported in the log, so I dunno.
