### ISSUE TITLE
Lint Not Working (after upgraded anaconda and reinstalled anaconda_go w/go 1.8)

### ISSUE THREAD

**Issue by uschen** [DamnWidget/anaconda_go#7]
Haven't changed any configurations.

On OS X
ST3

latest anaconda and anaconda_go

no console errors.

**Comment by DamnWidget** [comment]
Can you elaborate?
Did you installed anaconda_go for first time after install Go1.8 or you already had it installed before to install go1.8 with go1.7.5?

**Comment by uschen** [comment]
i had installed it before. 

after upgrade go1.8 from brew installation of 1.7 to official os x package 1.8, lint stopped working.
I uninstalled brew version and 1.8 and reinstalled 1.8 through official pkg.

reinstalled both anaconda_go and anaconda via package manager.

current config for anaconda_go is:
```
{
  "anaconda_go_linting": true,
  "anaconda_go_fast_linters_only": true,
  "anaconda_go_lint_test": true,
  "anaconda_go_max_line_length": 120,
  "anaconda_go_GOPATH": "/Users/me/go",
  "anaconda_go_GOROOT": "/usr/local/go",
  "anconda_go_guru_scope": "",
  "anaconda_go_guru_usage": "never",
  "anaconda_go_packages_cache_persistence": true,
  "env": {
    "GOPATH": "/Users/me/go",
    "GOROOT": "/usr/local/go"
  },
  "anaconda_go_gocyclo_threshold": 20,
  "anaconda_go_linters": [
    { "anaconda_go_aligncheck": true },
    { "anaconda_go_deadcode": true },
    { "anaconda_go_dupl": true },
    { "anaconda_go_errcheck": true },
    { "anaconda_go_gas": true },
    { "anaconda_go_goconst": true },
    { "anaconda_go_gocyclo": true },
    { "anaconda_go_golint": true },
    { "anaconda_go_gosimple": true },
    { "anaconda_go_gotype": true },
    { "anaconda_go_ineffassign": true },
    { "anaconda_go_interfacer": true },
    { "anaconda_go_staticcheck": true },
    { "anaconda_go_structcheck": true },
    { "anaconda_go_unconvert": true },
    { "anaconda_go_varcheck": true },
    { "anaconda_go_vet": true },
    { "anaconda_go_vetshadow": true },
    { "anaconda_go_test": false },
    { "anaconda_go_lll": false },
    { "anaconda_go_testify": false },
    { "anaconda_go_unused": false }
  ]
}

```

**Comment by uschen** [comment]
anaconda config:
```
{
      "python_interpreter": "/usr/local/bin/python3",
      "anaconda_debug": false,
      "auto_python_builder_enabled": false,
      "anaconda_gutter_theme": "retina",
      "anaconda_linter_show_errors_on_save": true
}
```

removed the cache for anaconda_go at ~/Libaray/Applic......./Cache/anaconda after reinstall

**Comment by uschen** [comment]
after sublime restart, the console log:
```
anaconda_go: finished detecting environment in 0.0011758804321289062s
```

format and all other anaconda_go functionalities are still working, like format, autocomplete are working, but just not lint ...

**Comment by DamnWidget** [comment]
You have to recompile the packages in your `$GOPATH` or at least reinstall the ones related with anaconda.

```
go get -u -f  gopkg.in/alecthomas/gometalinter.v1
go get -u -f  github.com/nsf/gocode
go get -u -f  github.com/DamnWidget/godef
go get -u -f  golang.org/x/tools/cmd/guru
go get -u -f  github.com/fatih/motion
go get -u -f  github.com/josharian/impl
go get -u -f  github.com/nsf/gocode
go get -u -f  github.com/zmb3/gogetdoc
```
Then reinstall gometalinter linters
```
gometalinter.v1 --install -u -f
```
That should fix any problem related with the go version bump.

**Comment by uschen** [comment]
@DamnWidget went through those. still no hint

**Comment by uschen** [comment]
before the last `re-install`. I started over with a clean $GOPATH

**Comment by DamnWidget** [comment]
Can you check logs in `~/Application\ Support/Logs/Anaconda` or `~/Application\ Support/Anaconda/logs`?

**Comment by uschen** [comment]
@DamnWidget 
no those folders.

`~/Library/Application\ Support/Anaconda` doesn't have `logs`

**Comment by uschen** [comment]
i wonder if i can add some `print` lines in 
https://github.com/DamnWidget/anaconda_go/blob/4cd9214e7052c3cb706ff8851040fcf99bfef41b/plugin/handlers_go/commands/lint.py#L23

so it will print out to ST's console

**Comment by uschen** [comment]
added a `print` in the beginning of `run` 
```
print('gometalinter: {}'.format(self.cmdline))
```

nothing get printed out.

**Comment by uschen** [comment]
@DamnWidget added `on_failure=print` to the Callback
got this
```
{'error': 'WARNING: exec: "go": executable file not found in $PATH\nWARNING: exec: "go": executable file not found in $PATH\n', 'success': False, 'vid': 31}
```

**Comment by uschen** [comment]
solved by
```
ln -s /usr/local/go/bin/go /usr/local/bin/go
```

Thanks @DamnWidget for the helps and great plugin!
