### ISSUE TITLE
executables assumed to live in $GOPATH/bin

### ISSUE THREAD

**Issue by justinfx** [DamnWidget/anaconda_go#8]
On both Linux and OSX I have seen failures to find required executables because anaconda_go assumes they should be at `$GOPATH/bin`. But on both these systems I set `$GOBIN` to control where binaries get installed. 

`$GOBIN` should be checked first before falling back on `$GOPATH/bin`

**Comment by alecthomas** [comment]
Also, not sure if this is an issue or not, but of course GOPATH can contain multiple paths, and consequently multiple bin directories.

**Comment by DamnWidget** [comment]
I will release a fix for both problems later today. In the case of the multiple `GOPATH` the plugin will traverse them until the binary is found with the same precedence than the `PATH` environment variables has (from left to right)
